name: CI - CRUD Inventario de Productos

on:
  push:
    branches: [ "CRUD-Inventario-de-Productos" ]
  pull_request:
    branches: [ "CRUD-Inventario-de-Productos" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout del repositorio
        uses: actions/checkout@v4

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"   # versión de Python para mi proyecto

      - name: 📦 Instalar dependencias (Django y librerías necesarias)
        run: |
          python -m pip install --upgrade pip
          pip install django

      - name: ⚙️ Aplicar migraciones
        run: |
          python manage.py migrate

      - name: ✅ Ejecutar pruebas
        run: |
          python manage.py test
